name: Push to main branch

on:
  push:
    branches:
      - main

jobs:
  check-coding-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - name: Install Flake8 dependencies
        run: python -m pip install -U flake8
      - name: Run Flake8
        run: flake8 .
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # caching pip dependencies
      - name: Install package in editable mode
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Install Test dependencies
        run: |
          pip install -r tests/requirements.txt
      - name: Test with pytest
        run: |
          python -m pytest
  build-sphinx-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - name: Install package dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install documentation requirements
        run: |
          pip install -r docs/requirements.txt
      - name: Build documentation
        run: |
          sphinx-build -b html ./docs/source ./docs/build/html
  build-package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # caching pip dependencies
      - name: Install build dependencies
        run: python -m pip install -U setuptools wheel build
      - name: Build the package
        run: python -m build .
